//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int Id { get; set; }
        public int IdPrestadora { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Prestadora Prestadora { get; set; }
    }
}
